pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/IamY0uu/JenkinsDemo.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Terraform') {
                    sh 'terraform plan -var-file=terraform.tfvars'
                }
            }
        }

stage('Terraform Apply') {
    steps {
        dir('Terraform') {
            script {
                try {
                    sh 'terraform apply -auto-approve -var-file=terraform.tfvars'
                } catch (err) {
                    echo "Apply failed, cleaning up..."
                    sh 'terraform destroy -auto-approve -var-file=terraform.tfvars || true'
                    error("Terraform apply failed: ${err}")
                }
            }
        }
    }
}

    
    post {
        success {
            echo 'Infrastructure provisioned successfully.'
        }
    }
}
}